export const table = [
    {
        cualidad: "Edición de video de hasta [X] minutos de metraje",
        basica: true,
        masElegida: true,
        premium: true,
    },
    {
        cualidad: "Corte y recorte de metraje",
        basica: true,
        masElegida: true,
        premium: true,
    },
    {
        cualidad: "Ajuste básico de colores y brillo",
        basica: true,
        masElegida: true,
        premium: true,
    },
    {
        cualidad: "Inclusión de música de fondo sin licencia",
        basica: true,
        masElegida: true,
        premium: true,
    },
    {
        cualidad: "Añadir transiciones sencillas",
        basica: true,
        masElegida: true,
        premium: true,
    },
    {
        cualidad: "Edición de audio para mejorar la calidad del sonido",
        basica: false,
        masElegida: true,
        premium: true,
    },
    {
        cualidad: "Inclusión de música de fondo personalizada o licenciada",
        basica: false,
        masElegida: true,
        premium: true,
    },
    {
        cualidad: "Efectos visuales y transiciones más elaboradas",
        basica: false,
        masElegida: true,
        premium: true,
    },
    {
        cualidad: "Títulos y subtítulos personalizados",
        basica: false,
        masElegida: true,
        premium: true,
    },
    {
        cualidad: "Corrección de color avanzada",
        basica: false,
        masElegida: false,
        premium: true,
    },
    {
        cualidad: "Animaciones y efectos especiales",
        basica: false,
        masElegida: false,
        premium: true,
    },
    {
        cualidad: "Exportación en calidad estándar (p. ej., 720p)",
        basica: true,
        masElegida: true,
        premium: true,
    },
    {
        cualidad: "Exportación en calidad Full HD (1080p)",
        basica: false,
        masElegida: true,
        premium: true,
    },
    {
        cualidad: "Exportación en calidad 4K o calidad personalizada",
        basica: false,
        masElegida: false,
        premium: true,
    },
    {
        cualidad: "Número limitado de revisiones (p. ej., 2 revisiones)",
        basica: true,
        masElegida: true,
        premium: true,
    },
    {
        cualidad: "Mayor número de revisiones (p. ej., 4 revisiones)",
        basica: false,
        masElegida: true,
        premium: true,
    },
    {
        cualidad: "Revisiones ilimitadas",
        basica: false,
        masElegida: false,
        premium: true,
    },
    {
        cualidad: "Servicio de atención al cliente prioritario",
        basica: false,
        masElegida: false,
        premium: true,
    },
];
